### PR TITLE
Super 

### PR DESCRIPTION
**Pull request by solomello21**
Plrase

### CODE REVIEW

**Comment by solomello21** [comment]
I needed it

**Comment by solomello21** [comment]
Ineedit

**Comment by Andrew-Hernandez** [comment]
How do I execute it on replit?

**Comment by slambo311** [comment]
Dude, nobody knows what the hell you're talking about.

**Comment by slambo311** [comment]
Also, this is not what pull requests are for. Use issues.

**Comment by slambo311** [comment]
Not only that, but the game's not being updated anymore. Seriously though, you're clearly an idiot.

**Comment by Andrew-Hernandez** [comment]
Well, this category is not called "issues" to your knowledge. Second, I don't see anyone besides you and me. Thirdly, maybe you should have done a bit of research before talking to me. @slambo311

**Comment by slambo311** [comment]
You're dumb enough to have your real name as your username, man. Plus, solomello's here. YOU should be the one researching.

**Comment by Andrew-Hernandez** [comment]
Here is more information, because you’re lacking of it.

[Linus Torvalds](https://github.com/torvalds)
[Vineet Grupart](https://github.com/vineetgarc)
There are some more, but Im to lazy to do it….

Besides, its seems that your professionalism is at its minimum. Please, educate yourself sociality; and then I can talk to you.

**Comment by Andrew-Hernandez** [comment]
Also, you don't even know if that's my real name? Hugh? 
Use your head for god's sake!

**Comment by Andrew-Hernandez** [comment]
Hope this message will make you understand that you're being disruptive to someone that is trying to learn...

**Comment by slambo311** [comment]
> Let me tell you something, You are being inconsiderate and I need you to stop. I calmly asked a question and for _no reason_ you just jumped and said _"you're clearly an idiot"_. Right now, you're trying to be a narcissist, or in other words someone who doesn't have a moral foundation. Besides, if you want to know; my ego is well kept in my imagination, and will never be brought to real life.

I called solomello an idiot, and mistook you for solomello. Plus, you keep acting like I'm the idiot here, while in fact it is both of us, because we're arguing over one simple mistake I made.

**Comment by 28klotlucas2** [comment]
Please put questions in "issues" next time. Download the zip and extract the files inside of an "html5" project.

**Pull request closed without merging**
